### PR TITLE
create content proposal

### PR DESCRIPTION
**Pull request by codyloyd**
basically a duplication of the original sample-proposal, but with sections more targeted for content-creation.

### CODE REVIEW

**Comment by leosoaivan** [comment]
It's alright I guess 🔥

**Comment by bycdiaz** [comment]
@codyloyd I know that timelines may  be very fluid at this point, but I'm wondering if it's worth having a projected time to completion in the proposal.

**Comment by KevinMulhern** [comment]
Looks great to me 😍

The basic outline section will finally give those a place to live.

**Comment by codyloyd** [comment]
@bycdiaz what purpose would a timeline serve

**Comment by bycdiaz** [comment]
@codyloyd if the proposal is meant to get a sense of the feasibility, I think we'd want to know if it would take a few hours vs a few months. Probably not super valuable for anyone not actively working on the proposed task, but giving a potential timeline could help the folks proposing the idea in their thinking.

**Comment by codyloyd** [comment]
i guess my main concern with the timeline is that it is almost impossible to guess.. making it pretty pointless.

**Comment by I3uckwheat** [comment]
@codyloyd It may be nice to have a "possible resources" section to outline some of the main resources people would plan to use for this project. Could help prevent another Hartl situation.

**Comment by codyloyd** [comment]
I can dig it

**Comment by codyloyd** [comment]
Gonna merge this then... further improvements/suggestions can come as a or issue

**Pull request merged**
